development:
  sessions:
    default:
      database: acl
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: acl_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>